### PR TITLE
Make the mouse blob move with a slight delay

### PR DESCRIPTION
**Pull request by andriemc**
This is self-explanatory, did it using `.animate();`.

**This isn't anything special.**

### CODE REVIEW

**Comment by andriemc** [comment]
Tiny Preview: https://andriemc.github.io/bedantadey17.github.io/ (That is somewhat broken btw.)

**Comment by andriemc** [comment]
Message from Bedenta: `it feels kinda laggy` (not merging it for now)

**Comment by bedantadey17** [comment]
i will consider this later ig, not closing though

**Comment by bedantadey17** [comment]
merged

**Comment by bedantadey17** [comment]
lock convo

**Pull request merged**
